// TruthLens — Supabase Edge Function: verify-image
// Performs deep multimodal Chain-of-Thought forensic analysis on images.
// API keys read from Deno.env — never exposed to the browser.
// Deploy: npx supabase functions deploy verify-image --project-ref tspmlmpkspffsghubxyz

import { serve } from "https://deno.land/std@0.177.0/http/server.ts";

// ── CORS — wildcard origin, all required methods ──────────────────────────────
const CORS_HEADERS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS, PUT, DELETE",
};

// ── Vision models — gemini-1.5-pro is the primary forensic model ──────────────
// Only confirmed models that accept multimodal inline_data via v1beta REST API.
const VISION_MODELS = [
  "gemini-1.5-pro",
  "gemini-1.5-flash",
  "gemini-2.0-flash",
];

// ── Chain-of-Thought Forensic System Prompt ───────────────────────────────────
const FORENSIC_SYSTEM_PROMPT = `You are TruthLens Forensics, the world's most accurate AI image authentication engine.

Your task is to perform a rigorous, multi-step Chain-of-Thought forensic inspection of the provided image to determine whether it was:
- Generated by an AI (Midjourney, DALL-E, Stable Diffusion, Flux, Firefly, etc.)
- Captured by a real camera (authentic photograph)
- Digitally manipulated (real photo with AI/Photoshop edits)

## CHAIN-OF-THOUGHT INSPECTION PROTOCOL

Think through EACH category methodically before forming a verdict:

### STEP 1 — ANATOMY CHECK
Hunt specifically for:
- Hands/fingers: count digits (AI frequently generates 4 or 6), look for fused knuckles, boneless bends, or phantom fingers
- Eyes: check for glassy synthetic catchlights, perfect bilateral symmetry, missing capillaries and natural redness
- Ears: AI ears often lack helix detail and are perfectly symmetrical
- Teeth: overly perfect, uniform white rows without individual variation
- Skin: poreless, wax-like smoothness with no pores, fine hairs, moles, or texture variation

### STEP 2 — LIGHTING & SHADOW ANALYSIS
Hunt specifically for:
- Shadow direction consistency across all objects (AI often mismatches shadow angles)
- Specular highlights: real cameras create natural hot-spots; AI creates perfectly diffuse, studio-like lighting
- Sub-surface scattering in skin (real skin glows slightly red near light sources)
- Catch-lights in eyes — AI often places perfect symmetrical dots; real reflections are irregular

### STEP 3 — TEXTURE FORENSICS
Hunt specifically for:
- Fabric: AI fabric has uniform, pattern-repeated texture; real fabric has natural wrinkles, pulls, and weight
- Hair strands: AI hair is often "painted on" with merged individual strands or unnatural uniformity
- Skin texture: AI skin is smooth and poreless; real skin has micro-texture variation visible at 1:1
- Background blur: AI applies mathematically perfect bokeh; real lenses have irregular aberrations
- Surface materials: AI renders materials uniformly (all glass looks the same); real materials have unique imperfections

### STEP 4 — GEOMETRY & PERSPECTIVE CHECK
Hunt specifically for:
- Background text, signs, or labels — AI produces garbled pseudo-letters or melted words
- Architectural lines — AI buildings often have impossible angles, warped walls, or non-Euclidean spaces
- Object physics — AI frequently places objects that defy gravity or clip through each other
- Crowds or repeated elements — AI backgrounds with people often show faceless blobs or copy-pasted faces

### STEP 5 — COMPRESSION & SENSOR ARTIFACT ANALYSIS
Hunt specifically for:
- JPEG compression block artifacts — real photos have natural 8x8 pixel blocking; AI images often do not
- ISO noise grain — real photos show organic luminance noise in shadows; AI images are often noise-free or have synthetic noise
- Chromatic aberration — real lenses create slight color fringing at high-contrast edges; AI images rarely have authentic CA
- Moiré patterns on textured surfaces — real photos of fabric/screens often exhibit moiré; AI-generated versions may not

## OUTPUT SCHEMA (MANDATORY — strict JSON only, no markdown, no backticks)
{
  "verdict": "AI Generated" | "Likely Real" | "Manipulated",
  "confidence": <integer 75-99>,
  "generalReasoning": "<2-3 sentences summarizing your overall conclusion and most decisive evidence>",
  "forensicDetails": [
    {
      "category": "Anatomy" | "Lighting" | "Textures" | "Geometry" | "Artifacts",
      "detail": "<specific, concrete observation — name the exact feature and what is wrong or right about it>",
      "locationHint": "<where in the image — e.g. 'subject's right hand', 'upper-left background', 'bottom edge', 'entire image'>",
      "severity": "high" | "medium" | "low"
    }
  ]
}

RULES:
- forensicDetails MUST have at least 3 entries, ideally 4-6 with concrete observations
- Each entry must name a SPECIFIC visual element (not "the image looks AI generated")
- locationHint must be a precise spatial description
- Do NOT include any text outside the JSON object
- severity "high" = decisive evidence for verdict, "medium" = supporting, "low" = minor indicator`;

// ── Helpers ───────────────────────────────────────────────────────────────────
function safeExtractJSON(text: string): Record<string, unknown> | null {
  if (!text) return null;
  const cleaned = text.replace(/```json/gi, "").replace(/```/g, "").trim();
  try {
    return JSON.parse(cleaned);
  } catch {
    const firstBrace = cleaned.indexOf("{");
    const lastBrace = cleaned.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace > firstBrace) {
      try {
        return JSON.parse(cleaned.substring(firstBrace, lastBrace + 1));
      } catch {
        // fall through
      }
    }
  }
  return null;
}

function aggressiveClean(text: string): string {
  return text
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .replace(/,\s*([}\]])/g, "$1")
    .replace(/[\u0000-\u001F\u007F]/g, " ")
    .trim();
}

// ── Main Handler ──────────────────────────────────────────────────────────────
serve(async (req: Request) => {
  const cors = CORS_HEADERS;

  // Handle CORS preflight — must return 204 with CORS headers
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: cors });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method Not Allowed" }), {
      status: 405,
      headers: { ...cors, "Content-Type": "application/json" },
    });
  }

  const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY") ?? "";
  if (!GEMINI_API_KEY) {
    console.error("CRITICAL: GEMINI_API_KEY is not set in Supabase secrets.");
    return new Response(
      JSON.stringify({
        verdict: "Error",
        confidence: 0,
        generalReasoning: "Server configuration error: GEMINI_API_KEY is missing from Supabase secrets. Run: npx supabase secrets set GEMINI_API_KEY=\"your-key\" --project-ref tspmlmpkspffsghubxyz",
        forensicDetails: [],
      }),
      { status: 500, headers: { ...cors, "Content-Type": "application/json" } },
    );
  }

  let body: { imageBase64?: string; mimeType?: string; fileName?: string };
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON body" }), {
      status: 400,
      headers: { ...cors, "Content-Type": "application/json" },
    });
  }

  const { imageBase64: rawInput, mimeType = "image/jpeg", fileName = "image" } = body;
  if (!rawInput) {
    return new Response(
      JSON.stringify({
        error: "imageBase64 is required",
        verdict: "Error",
        confidence: 0,
        generalReasoning: "No image data provided.",
        forensicDetails: [],
      }),
      { status: 400, headers: { ...cors, "Content-Type": "application/json" } },
    );
  }

  // Strip any data URL prefix (e.g. "data:image/jpeg;base64,") — Gemini API
  // requires the raw base64 string only, with no header prefix.
  const imageBase64 = rawInput.includes(",") ? rawInput.split(",")[1] : rawInput;

  // ── Multi-model fallover loop ─────────────────────────────────────────────
  let lastError: Error | null = null;

  for (const model of VISION_MODELS) {
    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 25000); // 25s timeout

      let nativeRes: Response;
      try {
        nativeRes = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            signal: controller.signal,
            body: JSON.stringify({
              system_instruction: {
                parts: [{ text: FORENSIC_SYSTEM_PROMPT }],
              },
              contents: [
                {
                  parts: [
                    {
                      text: `Perform a complete forensic inspection of this image (filename: "${fileName}"). Follow the Chain-of-Thought protocol precisely and return the strict JSON schema.`,
                    },
                    {
                      inline_data: {
                        mime_type: mimeType,
                        data: imageBase64,
                      },
                    },
                  ],
                },
              ],
              generationConfig: {
                temperature: 0.0,
                responseMimeType: "application/json",
              },
            }),
          },
        );
      } finally {
        clearTimeout(timer);
      }

      if (!nativeRes.ok) {
        const errBody = await nativeRes.text().catch(() => "");
        console.warn(`Model ${model} returned ${nativeRes.status}:`, errBody.slice(0, 200));
        lastError = new Error(`${nativeRes.status} from ${model}`);
        continue;
      }

      const nativeData = await nativeRes.json();
      const rawText = nativeData.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!rawText) {
        console.warn(`Model ${model}: empty response`);
        lastError = new Error(`Empty response from ${model}`);
        continue;
      }

      const parsed = safeExtractJSON(aggressiveClean(rawText));

      if (
        parsed &&
        (parsed.verdict || parsed.generalReasoning) &&
        Array.isArray(parsed.forensicDetails)
      ) {
        // Normalise verdict
        const rawVerdict = String(parsed.verdict || "").toLowerCase();
        let normVerdict: string;
        if (rawVerdict.includes("manipulat")) normVerdict = "Manipulated";
        else if (rawVerdict.includes("real") || rawVerdict.includes("authentic") || rawVerdict.includes("likely real")) normVerdict = "Likely Real";
        else normVerdict = "AI Generated";

        return new Response(
          JSON.stringify({
            verdict: normVerdict,
            confidence: Math.min(99, Math.max(75, Number(parsed.confidence) || 85)),
            generalReasoning: parsed.generalReasoning || "Forensic inspection completed.",
            forensicDetails: (parsed.forensicDetails as Array<Record<string, unknown>>).map((d) => ({
              category: d.category || "Artifacts",
              detail: d.detail || "",
              locationHint: d.locationHint || "unspecified",
              severity: d.severity || "medium",
            })),
            modelUsed: model,
          }),
          { status: 200, headers: { ...cors, "Content-Type": "application/json" } },
        );
      }

      console.warn(`Model ${model}: response missing required fields`, rawText.slice(0, 300));
      lastError = new Error(`Schema mismatch from ${model}`);
    } catch (err) {
      lastError = err as Error;
      if ((err as Error).name === "AbortError") {
        console.warn(`Model ${model}: timed out after 25s`);
      } else {
        console.warn(`Model ${model} error:`, (err as Error).message);
      }
    }
  }

  // All models failed
  return new Response(
    JSON.stringify({
      verdict: "Error",
      confidence: 0,
      generalReasoning: `All vision models failed: ${lastError?.message || "unknown error"}`,
      forensicDetails: [],
    }),
    { status: 200, headers: { ...cors, "Content-Type": "application/json" } },
  );
});
